import { GoogleGeminiEffectDemo } from '@/components/GeminiEffect'
import { ThreeDMarqueeDemo } from '@/components/ThreeMarquee'
import React from 'react'


export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
      <GoogleGeminiEffectDemo/>
      <ThreeDMarqueeDemo/>
    </div>
  )
}
