import { AnimatedModalDemo } from '@/components/AnimatedModal';
import { AuroraBackgroundDemo } from '@/components/auroraBackDemo';
import React from 'react'


export const metadata = {
  title: "Pricing",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <div>
      <AuroraBackgroundDemo/>
    </div>
  )
}
